gene/protein:
  file_name: data/dpi/drug_bank_with_protein_attributes.csv
  idetifier_column: Gene Name
  modality_columns:
    - gene_sequence
    - gene_function
  model_name_for_each_modality:
    - unikei/bert-base-proteins
    - dmis-lab/biobert-v1.1
drug:
  file_name: data/dpi/new_drugbank_feature_base.csv
  idetifier_column: generic_name
  modality_columns:
    - smiles
    - descriptions
  model_name_for_each_modality:
    - ibm/MoLFormer-XL-both-10pct
    - dmis-lab/biobert-v1.1
